# permissions for end users to edit kroxyliciousproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kroxyliciousproxy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kroxylicious-operator
    app.kubernetes.io/part-of: kroxylicious-operator
    app.kubernetes.io/managed-by: kustomize
  name: kroxyliciousproxy-editor-role
rules:
- apiGroups:
  - proxy.kroxylicious.io
  resources:
  - kroxyliciousproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.kroxylicious.io
  resources:
  - kroxyliciousproxies/status
  verbs:
  - get
