---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - proxy.kroxylicious.io
  resources:
  - kroxyliciousproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.kroxylicious.io
  resources:
  - kroxyliciousproxies/finalizers
  verbs:
  - update
- apiGroups:
  - proxy.kroxylicious.io
  resources:
  - kroxyliciousproxies/status
  verbs:
  - get
  - patch
  - update
