apiVersion: proxy.kroxylicious.io/v1alpha1
kind: KroxyliciousProxy
metadata:
  labels:
    app.kubernetes.io/name: kroxyliciousproxy
    app.kubernetes.io/instance: kroxyliciousproxy-sample
    app.kubernetes.io/part-of: kroxylicious-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kroxylicious-operator
  name: kroxyliciousproxy-sample
spec:
  # TODO(user): Add fields here
